### ISSUE TITLE
Pretrained weights availability?

### ISSUE THREAD

**Issue by SK124** [rish-16/CycleGANsformer#4]
Hi rish-16, your work is pretty amazing, i was having the same idea and was trying to implement, lucky i came across your repository,thank you  for opensourcing it. I am working on a domain where i have very limited images ~1000 images at best so i was wondering if you could provide any pretrained weights trained on larger /common datasets in your experimental studies, i could use those as my inital checkpoint and fintune over it. Thanks again.

**Comment by rish-16** [comment]
Hello, thank you for reaching out.

This project is currently under development and is not ready for use yet.

**Comment by SK124** [comment]
Oh okay, godspeed!
