### ISSUE TITLE
Img2Img

### ISSUE THREAD

**Issue by zhangdan8962** [rish-16/CycleGANsformer#5]
Hi,

I am wondering if you have successfully implemented the model that supports the image-to-image task since the original TransGAN is only built for noise as input.

**Comment by rish-16** [comment]
Hey there,

This project is currently an inactive WIP that I'm slowly finishing up. I plan to test it on the image-to-image task (maybe the horses and zebras dataset) soon after. That was the main purpose I intend to have it for anyway.

Thank you for reaching out!

Cheers 😃
